import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import Provider from "./Provider";
import { useSession } from "@supabase/auth-helpers-react";
import Header from "@/components/Header";
import ReactQueryProvider from "@/components/ReactQueryProvider";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PDFChatty",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const session = useSession()
  return (
    <html lang="en">
      {/* <Provider mySession={session}> */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReactQueryProvider>

        <main className="h-dvh bg-background flex flex-col items-center justify-center relative overflow-hidden">
          <Header />
          {children}
        </main>
        </ReactQueryProvider>
        <Toaster richColors position="bottom-right" />
      </body>
      {/* </Provider> */}
    </html>
  );
}
